name:                constraints-deriving
version:             1.1.0.0
github:              "achirkin/constraints-deriving"
license:             BSD3
author:              "Artem Chirkin"
maintainer:          "achirkin@users.noreply.github.com"
copyright:           "Copyright: (c) 2019 Artem Chirkin"
synopsis:            Manipulating constraints and deriving class instances programmatically.
category:            Constraints
description:         The library provides a plugin to derive class instances programmatically.
                     Please see the README on GitHub at <https://github.com/achirkin/constraints-deriving#readme>

extra-source-files:
- README.md
- test/Spec/*.hs
- test/out/*.stderr
- test/out/*.stdout

flags:

  constraints:
    description:
      Use vanilla constraints package as a dependency
      instead of the manual minimalistic definitions copied from there.
    default: false
    manual: true

  examples:
    description:
      Whether to build examples
    default: false
    manual: true

  debug:
    description:
      Show debug trace info (used only for library development).
      Note, if you want to see the debug output of the plugin in another project,
      you may need to manually define a CPP option -DPLUGIN_DEBUG in that project.
    default: false
    manual: true

ghc-options: -Wall

dependencies:
- base >= 4.9 && < 5

custom-setup:
  dependencies:
  - base
  - Cabal

library:
  source-dirs: src
  dependencies:
  - ghc >= 8.0.1
  exposed-modules:
  - Data.Constraint.Bare
  - Data.Constraint.Deriving
  - Data.Constraint.Deriving.ClassDict
  - Data.Constraint.Deriving.DeriveAll
  - Data.Constraint.Deriving.ToInstance
  other-modules:
  - Data.Constraint.Deriving.CorePluginM
  when:
  - condition: flag(debug)
    cpp-options: -DPLUGIN_DEBUG
  - condition: flag(constraints)
    then:
      dependencies:
      - constraints >= 0.6
    else:
      exposed-modules:
      - Data.Constraint
      - Data.Constraint.Unsafe
      source-dirs: src-constraints

tests:
  functional-tests:
    main:                Spec.hs
    source-dirs:         test
    other-modules:       []
    dependencies:
    - constraints-deriving
    - filepath
    - ghc
    - ghc-paths
    - path
    - path-io
    - bytestring

executables:
  deriving-example:
    when:
      - condition: flag(examples)
        then:
          ghc-options:
          - -dcore-lint
        else:
          buildable: false
    main:                Main.hs
    source-dirs:         example
    other-modules:
    - Lib.BackendFamily
    - Lib.VecBackend
    - Lib.Vector
    dependencies:
    - constraints-deriving
